name: ezeapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.1
  pinput: ^2.2.30

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/svg/

  fonts:
    - family: poppins
      fonts:  
        - asset: assets/google_fonts/Poppins-Medium.ttf
        - asset: assets/google_fonts/Poppins-Light.ttf

